# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'TestImageList' do
 pod 'SnapKit', '4.2.0'
 pod 'Alamofire'
 pod 'AlamofireImage'
end
